Fix/design issues
GWANoInstructor9-18/OperationRAK pull request #9
Opened 2018-10-25 04:12 UTC by jacob-rachal

There are still a few things I want to test/play around with, but for all intents and purposes this thing is now mobile-friendly. (I think I have some redundant code in the CSS that needs trimming.)

2018-10-25 22:35 UTC, anthony61016 approved these changes
looks good

2018-10-27 19:45 UTC, rehazler commented on index.html
> +	  <!-- <ul> -->
No need to comment stuff out. If you have confirmed that it is unnecessary, then just remove it entirely.

2018-10-27 19:47 UTC, rehazler commented on css/styles.css
> +  /* padding: 3px 53px; */
Same as the index file, trash the comment clutter.

2018-10-27 19:49 UTC, rehazler requested changes
In general it looks good from what I can tell. Only thing, across the files, there is no need to comment stuff out. If you have confirmed that it is unnecessary, then just remove it entirely. Trash the comment clutter.

2018-10-28 00:45 UTC, rehazler approved these changes
Lookin' good!

2018-10-29 03:00 UTC, merged